[workspace]
channels = ["conda-forge"]
name = "extract"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
codex = ">=0.87.0,<0.88"
ruff = ">=0.14.13,<0.15"

[pypi-dependencies]
langextract = ">=1.1.1, <2"
